/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import type { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "common": {
        "Hola": string;
        "\u00C9xito": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
