export const SystemModules = [
  'INSTITUTIONS',
  'LOCATIONS',
  'DISCIPLINES',
  'CATEGORIES',
  'ROLES',
  'PERMISSIONS',
  'USERS',
  'PERSONS',
  'CLUBS',
  'TEAMS',
  'PLAYERS',
  'TEAM_SEASONS',
  'STAFF',
  'TEAM_SEASON_STAFF',
  'SEASONS',
  'SCHOOLS',
  'COURSES',
  'COURSE_SEASONS',
  'COURSE_SEASON_STAFF',
  'STUDENTS',
  'PAYMENT_PLANS',
  'STUDENT_MEMBERSHIPS',
  'PLAYER_MEMBERSHIPS',
  'MEMBERSHIP_DISCOUNTS',
  'MEMBERSHIP_CHARGES',
  'STUDENT_CHARGES',
  'STUDENT_DISCOUNTS',
  'TRANSACTIONS',
  'SCHEDULES',
  'SESSIONS',
  'SESSION_BOOKINGS',
  'MATCHES',
  'MATCH_LINEUPS',
  'SESSION_INCIDENTS',
  'PROGRESS_EVALUATIONS',
  'AUDIT_LOGS',
  'DASHBOARD',
  'SHIFTS',
  'CHARGES',
  'SYSTEM',
] as const;

export type SystemModuleName = (typeof SystemModules)[number];

// Helper para generar permisos CRUD estándar
const crud = (module: string) => [
  `CREATE_${module}`,
  `READ_${module}`,
  `UPDATE_${module}`,
  `DELETE_${module}`,
];

// Mapa explícito de permisos por módulo
export const ModulePermissions: Record<SystemModuleName, string[]> = {
  INSTITUTIONS: crud('INSTITUTIONS'),
  LOCATIONS: crud('LOCATIONS'),
  DISCIPLINES: crud('DISCIPLINES'),
  CATEGORIES: crud('CATEGORIES'),
  ROLES: crud('ROLES'),
  PERMISSIONS: crud('PERMISSIONS'),
  USERS: crud('USERS'),
  PERSONS: crud('PERSONS'),
  CLUBS: crud('CLUBS'),
  TEAMS: crud('TEAMS'),
  PLAYERS: crud('PLAYERS'),
  TEAM_SEASONS: [
    ...crud('TEAM_SEASONS'),
    'FINISH_TEAM_SEASONS',
    'CANCEL_TEAM_SEASONS',
    'PAUSE_TEAM_SEASONS',
    'BILLING_TEAM_SEASONS',
  ],
  STAFF: crud('STAFF'),
  TEAM_SEASON_STAFF: crud('TEAM_SEASON_STAFF'),
  SEASONS: crud('SEASONS'),
  SCHOOLS: crud('SCHOOLS'),
  COURSES: crud('COURSES'),
  COURSE_SEASONS: crud('COURSE_SEASONS'),
  COURSE_SEASON_STAFF: crud('COURSE_SEASON_STAFF'),
  STUDENTS: crud('STUDENTS'),
  PAYMENT_PLANS: crud('PAYMENT_PLANS'),
  STUDENT_MEMBERSHIPS: crud('STUDENT_MEMBERSHIPS'),
  PLAYER_MEMBERSHIPS: crud('PLAYER_MEMBERSHIPS'),
  MEMBERSHIP_DISCOUNTS: crud('MEMBERSHIP_DISCOUNTS'),
  MEMBERSHIP_CHARGES: crud('MEMBERSHIP_CHARGES'),
  STUDENT_CHARGES: crud('STUDENT_CHARGES'),
  STUDENT_DISCOUNTS: crud('STUDENT_DISCOUNTS'),
  TRANSACTIONS: crud('TRANSACTIONS'),
  SCHEDULES: crud('SCHEDULES'),
  SESSIONS: crud('SESSIONS'),
  SESSION_BOOKINGS: crud('SESSION_BOOKINGS'),
  MATCHES: crud('MATCHES'),
  MATCH_LINEUPS: crud('MATCH_LINEUPS'),
  SESSION_INCIDENTS: crud('SESSION_INCIDENTS'),
  PROGRESS_EVALUATIONS: crud('PROGRESS_EVALUATIONS'),
  SHIFTS: crud('SHIFTS'),
  CHARGES: crud('CHARGES'),

  // Módulos especiales que no tienen CRUD completo
  AUDIT_LOGS: ['READ_AUDIT_LOGS'],
  DASHBOARD: ['READ_DASHBOARD'],
  SYSTEM: ['MANAGE_ALL'],
};

// Array plano con todos los permisos del sistema
export const AllSystemPermissions = Object.values(ModulePermissions).flat();
